services:
  feedback-panel:
    container_name: insight-feedback-panel
    restart: on-failure:2
    build:
      context: ../frontend/feedback-panel
      dockerfile: ./docker/dockerfile
    image: insight-feedback-panel-image:1.0
    networks:
      - insight-network
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: insight-nginx
    restart: on-failure:2
    build:
      context: ../nginx
      dockerfile: ./docker/dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - insight-network

networks:
  insight-network:
