services:
  postgres:
    restart: on-failure:2
    image: postgres:latest
    container_name: funitbv-postgresql
    env_file:
      - .env
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - funitbv-network
    # expose:
    #   - "5432"

  backend:
    container_name: funitbv-backend
    restart: on-failure:2
    image: funitbv-backend-image:1.0
    build:
      context: ../backend
      dockerfile: ../backend/docker/dockerfile
    networks:
      - funitbv-network
    depends_on:
      - postgres
    expose:
      - "8000"

  admin-panel:
    container_name: funitbv-admin-panel
    restart: on-failure:2
    build:
      context: ../frontend/admin-panel
      dockerfile: ./docker/dockerfile
    image: funitbv-admin-panel-image:1.0
    networks:
      - funitbv-network
    expose:
      - "3000"

  feedback-panel:
    container_name: funitbv-feedback-panel
    restart: on-failure:2
    build:
      context: ../frontend/feedback-panel
      dockerfile: ./docker/dockerfile
    image: funitbv-feedback-panel-image:1.0
    networks:
      - funitbv-network
    expose:
      - "3000"

  redis:
    image: redis:latest
    container_name: funitbv-redis
    restart: on-failure:2
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - funitbv-network
    volumes:
      - volume_redis:/data
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: funitbv-nginx
    restart: on-failure:2
    build:
      context: ../nginx
      dockerfile: ./docker/dockerfile
    ports:
      - "80:80"
      - "443:443"
    #  volumes:
    #    - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - funitbv-network

volumes:
  volume_postgres:
  volume_redis:

networks:
  funitbv-network:
