version: '1'
services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - feedback_network
  backend:
    container_name: backend_container
    restart: always
    image: backend_image:1.0
    build:
      context: ../Backend
      dockerfile: ../Docker/Dockerfile.backend
    networks:
      - feedback_network
    expose:
      - "5000"
    depends_on:
      - postgres
  frontend:
    container_name: frontend_container
    restart: always
    build:
      context: ../FrontEnd
      dockerfile: ../Docker/Dockerfile.frontend
    image: frontend_image:1.0
    networks:
      - feedback_network
    depends_on:
      - backend
    ports:
      - "3001"
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    container_name: mongodb_container
    env_file:
      - .env  
    volumes:
      - volume_mongodb:/data/db
    expose:
      - "27017"
    networks:
      - feedback_network
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    build:
      context: ../nginx
      dockerfile: ../Docker/Dockerfile.nginx
    ports:
      - "3000:3000"
    networks:
      - feedback_network
    depends_on:
      - frontend
      - backend
volumes:
  volume_postgres:
  volume_mongodb:
networks:
  feedback_network:
